import colors from "../locales/en/translation.json";
interface ColorRGB {
  r: number;
  g: number;
  b: number;
}

const clothesColors = Object.keys(colors).map((c) => c.toLowerCase());
export const normalizeColorName = (rawName: string) => {
  const normalized = rawName.replace(/\s+/g, "").toLowerCase();
  const match = clothesColors.find((c) => c === normalized);

  return match
    ? Object.keys(colors).find((key) => key.toLowerCase() === match)
    : "Unknown";
};

const hexToRgb = (hex: string): ColorRGB => {
  const cleaned = hex.replace("#", "");
  const bigint = parseInt(cleaned, 16);
  return {
    r: (bigint >> 16) & 255,
    g: (bigint >> 8) & 255,
    b: bigint & 255,
  };
};

export const findClosestColor = (hex: string): string => {
  const rgb = hexToRgb(hex);
  let closestName = "";
  let minDist = Infinity;

  for (const [name, colorHex] of Object.entries(colorsHex)) {
    const c = hexToRgb(colorHex);
    const dist = Math.sqrt(
      Math.pow(rgb.r - c.r, 2) +
        Math.pow(rgb.g - c.g, 2) +
        Math.pow(rgb.b - c.b, 2)
    );
    if (dist < minDist) {
      minDist = dist;
      closestName = name;
    }
  }
  return closestName;
};

export const colorMapping: Record<string, string> = {
  "Alice Blue": "AliceBlue",
  "Antique White": "AntiqueWhite",
  Aqua: "Aqua",
  Aquamarine: "Aquamarine",
  Azure: "Azure",
  Beige: "Beige",
  Bisque: "Bisque",
  Black: "Black",
  "Blanched Almond": "BlanchedAlmond",
  Blue: "Blue",
  "Blue Violet": "BlueViolet",
  Brown: "Brown",
  "Burly Wood": "BurlyWood",
  "Cadet Blue": "CadetBlue",
  Chartreuse: "Chartreuse",
  Chocolate: "Chocolate",
  Coral: "Coral",
  "Cornflower Blue": "CornflowerBlue",
  Cornsilk: "Cornsilk",
  Crimson: "Crimson",
  Cyan: "Cyan",
  "Dark Blue": "DarkBlue",
  "Dark Cyan": "DarkCyan",
  "Dark Goldenrod": "DarkGoldenRod",
  "Dark Gray": "DarkGray",
  "Dark Green": "DarkGreen",
  "Dark Khaki": "DarkKhaki",
  "Dark Magenta": "DarkMagenta",
  "Dark Olive Green": "DarkOliveGreen",
  "Dark Orange": "DarkOrange",
  "Dark Orchid": "DarkOrchid",
  "Dark Red": "DarkRed",
  "Dark Salmon": "DarkSalmon",
  "Dark Sea Green": "DarkSeaGreen",
  "Dark Slate Blue": "DarkSlateBlue",
  "Dark Slate Gray": "DarkSlateGray",
  "Dark Turquoise": "DarkTurquoise",
  "Dark Violet": "DarkViolet",
  "Deep Pink": "DeepPink",
  "Deep Sky Blue": "DeepSkyBlue",
  "Dim Gray": "DimGray",
  "Dodger Blue": "DodgerBlue",
  "Fire Brick": "FireBrick",
  "Floral White": "FloralWhite",
  "Forest Green": "ForestGreen",
  Fuchsia: "Fuchsia",
  Gainsboro: "Gainsboro",
  "Ghost White": "GhostWhite",
  Gold: "Gold",
  "Golden Rod": "GoldenRod",
  Gray: "Gray",
  Green: "Green",
  "Green Yellow": "GreenYellow",
  "Honey Dew": "HoneyDew",
  "Hot Pink": "HotPink",
  "Indian Red": "IndianRed",
  Indigo: "Indigo",
  Ivory: "Ivory",
  Khaki: "Khaki",
  Lavender: "Lavender",
  "Lavender Blush": "LavenderBlush",
  "Lawn Green": "LawnGreen",
  "Lemon Chiffon": "LemonChiffon",
  "Light Blue": "LightBlue",
  "Light Coral": "LightCoral",
  "Light Cyan": "LightCyan",
  "Light Goldenrod Yellow": "LightGoldenRodYellow",
  "Light Gray": "LightGray",
  "Light Green": "LightGreen",
  "Light Pink": "LightPink",
  "Light Salmon": "LightSalmon",
  "Light Sea Green": "LightSeaGreen",
  "Light Sky Blue": "LightSkyBlue",
  "Light Slate Gray": "LightSlateGray",
  "Light Steel Blue": "LightSteelBlue",
  "Light Yellow": "LightYellow",
  Lime: "Lime",
  "Lime Green": "LimeGreen",
  Linen: "Linen",
  Magenta: "Magenta",
  Maroon: "Maroon",
  "Medium Aqua Marine": "MediumAquaMarine",
  "Medium Blue": "MediumBlue",
  "Medium Orchid": "MediumOrchid",
  "Medium Purple": "MediumPurple",
  "Medium Sea Green": "MediumSeaGreen",
  "Medium Slate Blue": "MediumSlateBlue",
  "Medium Spring Green": "MediumSpringGreen",
  "Medium Turquoise": "MediumTurquoise",
  "Medium Violet Red": "MediumVioletRed",
  "Midnight Blue": "MidnightBlue",
  "Mint Cream": "MintCream",
  "Misty Rose": "MistyRose",
  Moccasin: "Moccasin",
  "Navajo White": "NavajoWhite",
  Navy: "Navy",
  "Old Lace": "OldLace",
  Olive: "Olive",
  "Olive Drab": "OliveDrab",
  Orange: "Orange",
  "Orange Red": "OrangeRed",
  Orchid: "Orchid",
  "Pale Goldenrod": "PaleGoldenRod",
  "Pale Green": "PaleGreen",
  "Pale Turquoise": "PaleTurquoise",
  "Pale Violet Red": "PaleVioletRed",
  "Papaya Whip": "PapayaWhip",
  "Peach Puff": "PeachPuff",
  Peru: "Peru",
  Pink: "Pink",
  Plum: "Plum",
  "Powder Blue": "PowderBlue",
  Purple: "Purple",
  "Rebecca Purple": "RebeccaPurple",
  Red: "Red",
  "Rosy Brown": "RosyBrown",
  "Royal Blue": "RoyalBlue",
  "Saddle Brown": "SaddleBrown",
  Salmon: "Salmon",
  "Sandy Brown": "SandyBrown",
  "Sea Green": "SeaGreen",
  "Sea Shell": "SeaShell",
  Sienna: "Sienna",
  Silver: "Silver",
  "Sky Blue": "SkyBlue",
  "Slate Blue": "SlateBlue",
  "Slate Gray": "SlateGray",
  Snow: "Snow",
  "Spring Green": "SpringGreen",
  "Steel Blue": "SteelBlue",
  Tan: "Tan",
  Teal: "Teal",
  Thistle: "Thistle",
  Tomato: "Tomato",
  Turquoise: "Turquoise",
  Violet: "Violet",
  Wheat: "Wheat",
  White: "White",
  "White Smoke": "WhiteSmoke",
  Yellow: "Yellow",
  "Yellow Green": "YellowGreen",
};

export const colorsHex: Record<string, string> = {
  AliceBlue: "#F0F8FF",
  AntiqueWhite: "#FAEBD7",
  Aqua: "#00FFFF",
  Aquamarine: "#7FFFD4",
  Azure: "#F0FFFF",
  Beige: "#F5F5DC",
  Bisque: "#FFE4C4",
  Black: "#000000",
  BlanchedAlmond: "#FFEBCD",
  Blue: "#0000FF",
  BlueViolet: "#8A2BE2",
  Brown: "#A52A2A",
  BurlyWood: "#DEB887",
  CadetBlue: "#5F9EA0",
  Chartreuse: "#7FFF00",
  Chocolate: "#D2691E",
  Coral: "#FF7F50",
  CornflowerBlue: "#6495ED",
  Cornsilk: "#FFF8DC",
  Crimson: "#DC143C",
  Cyan: "#00FFFF",
  DarkBlue: "#00008B",
  DarkCyan: "#008B8B",
  DarkGoldenRod: "#B8860B",
  DarkGray: "#A9A9A9",
  DarkGreen: "#006400",
  DarkKhaki: "#BDB76B",
  DarkMagenta: "#8B008B",
  DarkOliveGreen: "#556B2F",
  DarkOrange: "#FF8C00",
  DarkOrchid: "#9932CC",
  DarkRed: "#8B0000",
  DarkSalmon: "#E9967A",
  DarkSeaGreen: "#8FBC8F",
  DarkSlateBlue: "#483D8B",
  DarkSlateGray: "#2F4F4F",
  DarkTurquoise: "#00CED1",
  DarkViolet: "#9400D3",
  DeepPink: "#FF1493",
  DeepSkyBlue: "#00BFFF",
  DimGray: "#696969",
  DodgerBlue: "#1E90FF",
  FireBrick: "#B22222",
  FloralWhite: "#FFFAF0",
  ForestGreen: "#228B22",
  Fuchsia: "#FF00FF",
  Gainsboro: "#DCDCDC",
  GhostWhite: "#F8F8FF",
  Gold: "#FFD700",
  GoldenRod: "#DAA520",
  Gray: "#808080",
  Green: "#008000",
  GreenYellow: "#ADFF2F",
  HoneyDew: "#F0FFF0",
  HotPink: "#FF69B4",
  IndianRed: "#CD5C5C",
  Indigo: "#4B0082",
  Ivory: "#FFFFF0",
  Khaki: "#F0E68C",
  Lavender: "#E6E6FA",
  LavenderBlush: "#FFF0F5",
  LawnGreen: "#7CFC00",
  LemonChiffon: "#FFFACD",
  LightBlue: "#ADD8E6",
  LightCoral: "#F08080",
  LightCyan: "#E0FFFF",
  LightGoldenRodYellow: "#FAFAD2",
  LightGray: "#D3D3D3",
  LightGreen: "#90EE90",
  LightPink: "#FFB6C1",
  LightSalmon: "#FFA07A",
  LightSeaGreen: "#20B2AA",
  LightSkyBlue: "#87CEFA",
  LightSlateGray: "#778899",
  LightSteelBlue: "#B0C4DE",
  LightYellow: "#FFFFE0",
  Lime: "#00FF00",
  LimeGreen: "#32CD32",
  Linen: "#FAF0E6",
  Magenta: "#FF00FF",
  Maroon: "#800000",
  MediumAquaMarine: "#66CDAA",
  MediumBlue: "#0000CD",
  MediumOrchid: "#BA55D3",
  MediumPurple: "#9370DB",
  MediumSeaGreen: "#3CB371",
  MediumSlateBlue: "#7B68EE",
  MediumSpringGreen: "#00FA9A",
  MediumTurquoise: "#48D1CC",
  MediumVioletRed: "#C71585",
  MidnightBlue: "#191970",
  MintCream: "#F5FFFA",
  MistyRose: "#FFE4E1",
  Moccasin: "#FFE4B5",
  NavajoWhite: "#FFDEAD",
  Navy: "#000080",
  OldLace: "#FDF5E6",
  Olive: "#808000",
  OliveDrab: "#6B8E23",
  Orange: "#FFA500",
  OrangeRed: "#FF4500",
  Orchid: "#DA70D6",
  PaleGoldenRod: "#EEE8AA",
  PaleGreen: "#98FB98",
  PaleTurquoise: "#AFEEEE",
  PaleVioletRed: "#DB7093",
  PapayaWhip: "#FFEFD5",
  PeachPuff: "#FFDAB9",
  Peru: "#CD853F",
  Pink: "#FFC0CB",
  Plum: "#DDA0DD",
  PowderBlue: "#B0E0E6",
  Purple: "#800080",
  RebeccaPurple: "#663399",
  Red: "#FF0000",
  RosyBrown: "#BC8F8F",
  RoyalBlue: "#4169E1",
  SaddleBrown: "#8B4513",
  Salmon: "#FA8072",
  SandyBrown: "#F4A460",
  SeaGreen: "#2E8B57",
  SeaShell: "#FFF5EE",
  Sienna: "#A0522D",
  Silver: "#C0C0C0",
  SkyBlue: "#87CEEB",
  SlateBlue: "#6A5ACD",
  SlateGray: "#708090",
  Snow: "#FFFAFA",
  SpringGreen: "#00FF7F",
  SteelBlue: "#4682B4",
  Tan: "#D2B48C",
  Teal: "#008080",
  Thistle: "#D8BFD8",
  Tomato: "#FF6347",
  Turquoise: "#40E0D0",
  Violet: "#EE82EE",
  Wheat: "#F5DEB3",
  White: "#FFFFFF",
  WhiteSmoke: "#F5F5F5",
  Yellow: "#FFFF00",
  YellowGreen: "#9ACD32",
};
